from odoo import models, fields

class AccountAccount(models.Model):
    _inherit = "account.account"

    account_type = fields.Selection(
        selection_add=[
            ('net_net_sales', 'Net Sales (Sell-In)'),
            ('cogs_inward_logis_du', 'Inward Logistics - Duties and Taxes'),
            ('cogs_inward_logis_sh', 'Inward Logistics - Shipping Charges'),
           ('cogs_prod_charges', 'Production Charges'),
           ('cogs_raw_material', 'Raw Material and Packaging'),
           ('disexp_personal_cost', 'Personnel cost Distribution'),
           ('disexp_outgoing_sh', 'Outbound Shipping'),
           ('disexp_warehouse_op', 'Warehouse Operating Expenses'),
           ('disexp_warehouse_ren', 'Warehousing Rental'),
           ('sellingex_personnel_cost', 'Personnel cost Selling'),
           ('sellingex_affilate', 'Affiliate Commissions'),
           ('sellingex_boutique', 'Boutique Opex'),
           ('sellingex_card_fee', 'Card Fees'),
           ('sellingex_digital_service', 'Digital Services'),
           ('sellingex_influencer_comm', 'Influencer Commission'),
           ('sellingex_rental_bout', 'Rental - Boutiques'),
           ('sellingex_sales_comm', 'Sales Commissions'),
           ('sellingex_travel_exp', 'Travel Expenses'),
           ('marketexp_personal_cost', 'Personnel cost Marketing'),
           ('marketexp_advertising_cost_fb', 'Advertising Cost - Facebook (Retail/Ecom)'),
           ('marketexp_advertising_cost_google', 'Advertising Cost - Google (Retail/Ecom)'),
           ('marketexp_crm', 'CRM'),
           ('marketexp_event_5g', 'Event SG'),
           ('marketexp_other', 'Other A&P'),
           ('marketexp_pr_media', 'PR/ Media '),
           ('gaexp_personal_exp', 'Personnel cost G&A'),
           ('gaexp_bank_charges', 'Bank Charges'),
           ('gaexp_business_dev', 'Business Development'),
           ('gaexp_forex_rev', 'Forex Revaluation'),
           ('gaexp_insurance_exp', 'Insurance Expenses'),
           ('gaexp_office_opex', 'Office Opex'),
           ('gaexp_other_opex', 'Other Opex'),
           ('gaexp_pl_suspense', 'P/L Suspense'),
           ('gaexp_pro_fees', 'Professional Fees'),
           ('gaexp_rental_office', 'Rental - Office'),
           ('gaexp_tel_comm', 'Telecom and Communication'),
           ('depamor_dep_exp', 'Depreciation expenses'),
           ('depamor_amortisation_exp', 'Amortisation expenses'),
           ('depamor_dep_exp_irfs16', 'Depreciation expenses IRFS16'),
        ],
        ondelete={
             'net_net_sales':'cascade',
            'cogs_inward_logis_du':'cascade',
            'cogs_inward_logis_sh':'cascade',
           'cogs_prod_charges':'cascade',
           'cogs_raw_material':'cascade',
           'disexp_personal_cost':'cascade',
           'disexp_outgoing_sh':'cascade',
           'disexp_warehouse_op':'cascade',
           'disexp_warehouse_ren':'cascade',
           'sellingex_personnel_cost':'cascade',
           'sellingex_affilate':'cascade',
           'sellingex_boutique':'cascade',
           'sellingex_card_fee':'cascade',
           'sellingex_digital_service':'cascade',
           'sellingex_influencer_comm':'cascade',
           'sellingex_rental_bout':'cascade',
           'sellingex_sales_comm':'cascade',
           'sellingex_travel_exp':'cascade',
           'marketexp_personal_cost':'cascade',
           'marketexp_advertising_cost_fb':'cascade',
           'marketexp_advertising_cost_google':'cascade',
           'marketexp_crm':'cascade',
           'marketexp_event_5g':'cascade',
           'marketexp_other':'cascade',
           'marketexp_pr_media':'cascade',
           'gaexp_personal_exp':'cascade',
           'gaexp_bank_charges':'cascade',
           'gaexp_business_dev':'cascade',
           'gaexp_forex_rev':'cascade',
           'gaexp_insurance_exp':'cascade',
           'gaexp_office_opex':'cascade',
           'gaexp_other_opex':'cascade',
           'gaexp_pl_suspense':'cascade',
           'gaexp_pro_fees':'cascade',
           'gaexp_rental_office':'cascade',
           'gaexp_tel_comm':'cascade',
           'depamor_dep_exp':'cascade',
           'depamor_amortisation_exp':'cascade',
           'depamor_dep_exp_irfs16':'cascade',
        }
    )
    internal_group = fields.Selection(
        selection_add=[
            ('net', 'Net Sales (Sell-In)'),
            ('cogs', 'COGS'),
            ('disexp', 'Distribution Expenses'),
            ('sellingex', 'Selling expenses'),
            ('marketexp', 'Marketing expenses'),
            ('gaexp', 'G&A expenses'),
            ('depamor', 'Depricaition and Amortisation'),
            
        ],
        ondelete={
             'net':'cascade',
             'cogs':'cascade',
             'disexp':'cascade',
             'sellingex':'cascade',
             'marketexp':'cascade',
             'gaexp':'cascade',
             'depamor':'cascade',
            
        }
    )
